[package]
name = "market-data"
version = "0.1.0"
edition = "2021"

[dependencies]
orderbook = { path = "../orderbook" }
tokio = { workspace = true }
rand = { workspace = true }
chrono = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio-tungstenite = "0.24"
futures-util = "0.3"
anyhow = { workspace = true }
