// Include generated proto code
// This will be generated by build.rs at compile time
pub mod proto {
    #![allow(clippy::all)]
    include!("proto/execution.rs");
}

pub mod server;
pub mod types;

pub use server::*;
pub use types::*;
