[package]
name = "trader-gui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trader-gui"
path = "src/main.rs"

[dependencies]
eframe = { workspace = true }
egui_plot = "0.29"
tokio = { workspace = true }
tonic = { workspace = true }
env_logger = "0.11"

api = { path = "../api" }
orderbook = { path = "../orderbook" }
