[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
tokio-stream = "0.1"

orderbook = { path = "../orderbook" }
algo-core = { path = "../algo-core" }

[build-dependencies]
tonic-build = { workspace = true }
protoc-bin-vendored = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
