[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tokio-stream = { version = "0.1", features = ["net"] }

orderbook = { path = "../orderbook" }

[build-dependencies]
tonic-build = { workspace = true }
protoc-bin-vendored = { workspace = true }
