[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "engine"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

orderbook = { path = "../orderbook" }
algo-core = { path = "../algo-core" }
api = { path = "../api" }
config = { path = "../config" }

[dev-dependencies]
proptest = { workspace = true }
tonic = { workspace = true }
