[package]
name = "algo_exec_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "algo_exec_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

algo-core = { path = "../algo-core" }
orderbook = { path = "../orderbook" }
